### ISSUE TITLE
macOS has removed support for resource forks!

### ISSUE THREAD

**Issue by gingerbeardman** [thejoelpatrol/fusehfs#8]
In macOS (not sure since when, but I'm seeing this in Monterey 12.6.1) the resource fork part of files is no longer accessible. 

- contents wise we know it is there
- file space wise it is still there

But:

- macOS doesn't see the resource fork
- `xattr` doesn't show the resource fork
- apps that usually open a certain type of files no longer see them as valid, because they can't see the resource fork

So, even if we are now able to open an old disk using FuseHFS, the contents are not completely accessible.

Damn it, Apple!

## More info
- https://github.com/PierreLorenzi/HyperCardPreview/issues/16

**Comment by phcoder** [comment]
https://github.com/thejoelpatrol/fusehfs/pull/11 should help

**Comment by joevt** [comment]
I don't think this is a problem and should be closed.

**Comment by gingerbeardman** [comment]
I agree it's not a guards problem, but I'm unable to access files as you've seen in other bug reports.

I'm happy to close here.
